CREATE TYPE USER_TYPE_ENUM AS ENUM ('SUBSCRIBER', 'CUSTOMER');
ALTER TABLE AppUser ALTER COLUMN user_type DROP DEFAULT;
ALTER TABLE AppUser ALTER COLUMN user_type TYPE USER_TYPE_ENUM USING user_type::USER_TYPE_ENUM;
ALTER TABLE AppUser ALTER COLUMN user_type SET DEFAULT 'SUBSCRIBER'::USER_TYPE_ENUM;
