CREATE TYPE GENDER_ENUM AS ENUM ('ANOTHER', 'FEMALE', 'MALE');
ALTER TABLE AppUser ALTER COLUMN gender DROP DEFAULT;

CREATE OR REPLACE FUNCTION SMALLINT_CAST_GENDER_ENUM(i SMALLINT)
    returns GENDER_ENUM as $gender$
DECLARE
    i SMALLINT;
BEGIN
    IF i = 0 THEN
        return 'ANOTHER'::GENDER_ENUM;
    END IF;
    IF i = 1 THEN
        return 'FEMALE'::GENDER_ENUM;
    ELSE
        return 'MALE'::GENDER_ENUM;
    END IF;
END;
$gender$ LANGUAGE plpgsql;

CREATE CAST (SMALLINT as GENDER_ENUM) with function SMALLINT_CAST_GENDER_ENUM(SMALLINT);
ALTER TABLE AppUser ALTER COLUMN gender TYPE GENDER_ENUM USING gender::GENDER_ENUM;
ALTER TABLE AppUser ALTER COLUMN gender SET DEFAULT 'ANOTHER'::GENDER_ENUM;
